<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nama Sekolah SDN 1 KALIMANTANKoordinat _f7e765</name>
   <tag></tag>
   <elementGuidId>231ec4a6-751d-41dc-9e13-949bf401df7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#map</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='map']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9f0128cc-5760-4226-ac43-7c893d542a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>map</value>
      <webElementGuid>47a51227-285c-41b0-8e2f-0aae41ea1c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leaflet-container leaflet-touch leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom</value>
      <webElementGuid>9d613b07-4455-40ed-893f-833f92cabf35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>aa001834-5e35-41a7-95d7-c00d6f92bed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nama Sekolah: SDN 1 KALIMANTANKoordinat: -2.3133002287910425, 115.2772879600525×+− Leaflet</value>
      <webElementGuid>94ee4f2e-7bca-4115-8ff8-fd3dd1d9f9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;map&quot;)</value>
      <webElementGuid>bcbc00e2-92c6-42e9-90c7-cf74c9d35e68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='map']</value>
      <webElementGuid>8d2eff87-53b0-4f2a-809f-1e8b02624602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[6]/following::div[1]</value>
      <webElementGuid>be719ffe-8d4f-4fbe-b743-c59ec366c4e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Longitude'])[1]/following::div[1]</value>
      <webElementGuid>aaf9f64f-82fa-41d1-b592-e6124ed6108d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div</value>
      <webElementGuid>a2583eec-e46a-453f-a244-2f64dcd616e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'map' and (text() = 'Nama Sekolah: SDN 1 KALIMANTANKoordinat: -2.3133002287910425, 115.2772879600525×+− Leaflet' or . = 'Nama Sekolah: SDN 1 KALIMANTANKoordinat: -2.3133002287910425, 115.2772879600525×+− Leaflet')]</value>
      <webElementGuid>47deef97-01f6-41ce-aa42-db5dc1da71bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
