<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Leaflet</name>
   <tag></tag>
   <elementGuidId>79649543-80ec-4caa-8db1-4070cb5236ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#map</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='map']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b5b4db6a-a8aa-4ce3-a623-8f8ed562cd6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>map</value>
      <webElementGuid>128024c2-37d3-4ef1-8b8b-662924fda8be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leaflet-container leaflet-touch leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom</value>
      <webElementGuid>0072c56d-2f24-42a4-93d5-0c0e35112e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3d741aaa-1050-4b5f-852d-5a606626a352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+− Leaflet</value>
      <webElementGuid>62d1a40d-2914-4c1f-99ad-e095deadfb31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;map&quot;)</value>
      <webElementGuid>a3e17875-d747-498b-b4f3-8386b2b079ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='map']</value>
      <webElementGuid>40b1687b-2ad9-4dff-bbcd-490885e200b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[6]/following::div[1]</value>
      <webElementGuid>7493bbd4-11ef-4362-9757-e7a3bb5a3a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Longitude'])[1]/following::div[1]</value>
      <webElementGuid>f312f003-6843-44e9-b405-248779231614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/preceding::div[18]</value>
      <webElementGuid>01964d79-cda7-4a01-b99e-068482b9421e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div</value>
      <webElementGuid>d999111c-3d2f-4b26-8b17-644f7abc43df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'map' and (text() = '+− Leaflet' or . = '+− Leaflet')]</value>
      <webElementGuid>fe2fac66-bab4-430f-8e5a-dfba9489317c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
