<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__nama_sekolah</name>
   <tag></tag>
   <elementGuidId>f8272ee5-74f6-4821-bb65-813a55ec62fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InputNamaSekolah</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InputNamaSekolah']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>525f562a-0856-4a7c-b4ad-901559814720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>328bbf10-29d7-4247-b2ba-bd0b03f3bbb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_sekolah</value>
      <webElementGuid>10410bd1-6aa7-4d37-b526-00e322515bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InputNamaSekolah</value>
      <webElementGuid>17a89240-96e8-4b78-b215-171ab8861525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan nama sekolah</value>
      <webElementGuid>e21fefbe-9575-4d9f-8386-a0bbdf580949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bcca458a-f2eb-4d3a-8278-8581aaa02142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InputNamaSekolah&quot;)</value>
      <webElementGuid>fa6f22c9-13bc-4903-8fbc-1f14db74c4cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SDN 1 KALIMANTAN</value>
      <webElementGuid>dbf679cb-4c99-4c61-868b-89def5728294</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InputNamaSekolah']</value>
      <webElementGuid>03497af0-6032-43af-aad2-7fb7a4f6813c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>bb155b32-e00d-4622-8d33-a9510748176d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nama_sekolah' and @id = 'InputNamaSekolah']</value>
      <webElementGuid>b92624e6-895b-48ee-8e40-d71aa37f8e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nama_sekolah' and @id = 'InputNamaSekolah' and @placeholder = 'Masukkan nama sekolah']</value>
      <webElementGuid>875916ab-98e3-4b8c-8b7c-37bd17c47120</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
