<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__alamat</name>
   <tag></tag>
   <elementGuidId>18870dce-8b22-4cfb-b8c7-5134077fff13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InputAlamat</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InputAlamat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f27b6394-15b4-4478-b2aa-3e9228176715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>368efbca-c6ac-4da9-97fa-311912765a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>alamat</value>
      <webElementGuid>f87f0739-1929-4d7b-b06f-d493aa301d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InputAlamat</value>
      <webElementGuid>cb8c3a86-c292-403b-ac64-2aca4857323d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan alamat sekolah</value>
      <webElementGuid>52de8a70-fec8-4b47-a530-bc604083163c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d3251213-7613-4809-82bd-403aba56c65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InputAlamat&quot;)</value>
      <webElementGuid>d62e5e27-0243-4728-b692-1618123f73b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Jalan kalimantan</value>
      <webElementGuid>0518dfe2-ee02-4bcd-8cac-52d6fdc7b803</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InputAlamat']</value>
      <webElementGuid>bd89e131-0970-4385-ab7c-0a6598c080a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/input</value>
      <webElementGuid>774e96af-2828-463f-a33d-190c2d1a9860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'alamat' and @id = 'InputAlamat']</value>
      <webElementGuid>d98ae09d-3466-4c14-a5f4-31211972243a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'alamat' and @id = 'InputAlamat' and @placeholder = 'Masukkan alamat sekolah']</value>
      <webElementGuid>8a3df710-c8dc-44b6-b080-c1bd3ea3426a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
