<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>263dc3f3-0691-4e04-9b08-70b24fe2bdfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(19) > td.align-middle > div.d-flex.align-items-center > a.btn.btn-warning.mr-2.px-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='exemple2']/tbody/tr[19]/td[7]/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>14e310bf-85b6-41de-b174-d27b068e6e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://127.0.0.1:8000/sekolahs/133/edit</value>
      <webElementGuid>16a8ab22-7b0c-4044-8169-13728f047f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning mr-2 px-2</value>
      <webElementGuid>95c5394c-f2e6-477d-bc8b-1513d617398f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>5969171f-f36e-4594-ab25-99c53559afcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exemple2&quot;)/tbody[1]/tr[19]/td[@class=&quot;align-middle&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/a[@class=&quot;btn btn-warning mr-2 px-2&quot;]</value>
      <webElementGuid>2b4e38c4-7e81-4e76-9219-002f46176ff4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='exemple2']/tbody/tr[19]/td[7]/div/a[2]</value>
      <webElementGuid>54d5502f-db03-4f34-b4aa-5e248a69e7c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Edit')])[19]</value>
      <webElementGuid>12562cd6-5c93-4381-b8ba-7332b756fd82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat'])[19]/following::a[1]</value>
      <webElementGuid>fc5962f0-7821-475b-9788-fa151ca7b705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Benua Lawas'])[6]/following::a[2]</value>
      <webElementGuid>b22b4763-ea7d-401c-81d5-25bcebd96424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[19]/preceding::a[1]</value>
      <webElementGuid>cf221760-7736-4cd8-8d2a-de7b334adc9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://127.0.0.1:8000/sekolahs/133/edit']</value>
      <webElementGuid>33d531c5-22fa-4ce6-8c74-8c8bcb25ffd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[19]/td[7]/div/a[2]</value>
      <webElementGuid>48624f2b-a5f6-47bc-aa17-769759d469fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://127.0.0.1:8000/sekolahs/133/edit' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>7815da55-ec98-478b-92fb-153fe665058d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
