<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lihat</name>
   <tag></tag>
   <elementGuidId>d8739f27-383a-4790-aa7e-e99b9b40c497</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-lihat']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-lihat</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c24860a9-69f4-4876-9380-1f5d75bd9154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-lihat</value>
      <webElementGuid>5e8d20fe-ea94-4191-a9cb-766bd7051012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-lihat btn btn-success</value>
      <webElementGuid>3f77930c-0fff-4fca-9d8b-9ec5ec704ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lat</name>
      <type>Main</type>
      <value>-2.1426182346949134</value>
      <webElementGuid>4a720123-2919-45b8-b6de-9b666286ade8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lng</name>
      <type>Main</type>
      <value>115.39806582033636</value>
      <webElementGuid>da82b650-3af5-4bb6-8ce1-e83734f7b753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat</value>
      <webElementGuid>93fd688a-1c5c-4158-939e-940e0fe03f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sekolahTable&quot;)/tbody[1]/tr[1]/td[5]/button[@id=&quot;btn-lihat&quot;]</value>
      <webElementGuid>b60fc9ca-c4ee-4b9a-b700-d191f105f3b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-lihat']</value>
      <webElementGuid>2dd2eb4b-2e0f-4e03-b075-fdd080e7ba34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='sekolahTable']/tbody/tr/td[5]/button</value>
      <webElementGuid>c401c635-bcd5-432d-8dcd-d2265fafb095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Murung Pudak'])[3]/following::button[1]</value>
      <webElementGuid>e69a743c-b898-4db4-95bb-5e379e799028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jl.Gelatik Komplek Pertamina Murung Pudak Kab.Tabalong Prov. Kalimantan Selatan'])[1]/following::button[1]</value>
      <webElementGuid>d513f59e-c4d2-452f-865a-b83c0d3e618e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SMAN 2 TANJUNG'])[1]/preceding::button[1]</value>
      <webElementGuid>cd4e5622-6078-45ea-bf9d-86dc725b26ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SMA'])[4]/preceding::button[1]</value>
      <webElementGuid>7ec5bfbf-e17b-45eb-a0ea-6b3a6b7339f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lihat']/parent::*</value>
      <webElementGuid>b66bf972-4eed-4afa-91fb-12655ea7530d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>a0f4cff3-6c75-417f-af38-693d76944c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-lihat' and (text() = 'Lihat' or . = 'Lihat')]</value>
      <webElementGuid>cecdaecb-b42c-4a03-8f76-e9b75a989058</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
