<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Leaflet</name>
   <tag></tag>
   <elementGuidId>3a5b7109-34c1-4e31-a72a-462011efd8f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='map']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#map</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3ccfa5f1-b4dc-4294-a911-35f688bf05f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>map</value>
      <webElementGuid>49da2322-6707-477f-a59f-f459b7a66e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leaflet-container leaflet-touch leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom</value>
      <webElementGuid>a3f81838-0ce0-45dd-9199-09b331b2828b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5f37a897-533c-4136-9dec-9a5e7a5ad42a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+− Leaflet</value>
      <webElementGuid>1b22d5d6-f1da-48c5-8f21-bd2adffb5926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;map&quot;)</value>
      <webElementGuid>59ffda04-90f9-4ebf-8178-d4aae5d59925</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='map']</value>
      <webElementGuid>24b1f0ea-f1f5-4ba6-8ea5-54974492d020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peta Kabupaten Tabalong'])[1]/following::div[6]</value>
      <webElementGuid>9b194563-090e-4828-9764-538bfbadc156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Peta'])[1]/following::div[10]</value>
      <webElementGuid>12d7c8e8-5950-4eed-9cbf-06d9b9d30353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Sekolah'])[1]/preceding::div[21]</value>
      <webElementGuid>2cc39c10-0486-44a0-a8d4-b417f574de4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]</value>
      <webElementGuid>d81b62e0-77c2-4e1b-bcb2-154557c66d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'map' and (text() = '+− Leaflet' or . = '+− Leaflet')]</value>
      <webElementGuid>0ac0aec6-886d-4968-a553-0bd05aa73716</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
