<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Peta Kabupaten Tabalong_leaflet-marker-_706ec2</name>
   <tag></tag>
   <elementGuidId>de95f506-a1ca-4517-9ae4-a25db80603f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='map']/div/div[4]/img[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fab175f0-1eae-44da-a6ae-b06e6a9e41d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png</value>
      <webElementGuid>8e485075-f3ad-435c-a781-fee36ebc7150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leaflet-marker-icon leaflet-zoom-animated leaflet-interactive</value>
      <webElementGuid>03d46eca-e363-44a7-afd1-f4d943fe273b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Marker</value>
      <webElementGuid>b7cf98a8-1cd9-4b6c-86f6-8ec91f66e3b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>54524a85-fc11-4012-89da-8ffd32b7f312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d01a6f07-e0a6-4e3b-a49b-5ae95c6f5813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;map&quot;)/div[@class=&quot;leaflet-pane leaflet-map-pane&quot;]/div[@class=&quot;leaflet-pane leaflet-marker-pane&quot;]/img[@class=&quot;leaflet-marker-icon leaflet-zoom-animated leaflet-interactive&quot;]</value>
      <webElementGuid>2075e4d8-ce37-4d0e-b2d0-d23d0b452bcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='map']/div/div[4]/img[2]</value>
      <webElementGuid>4055ea35-c613-479b-9610-0b279b427faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Marker'])[2]</value>
      <webElementGuid>4620bb27-d3cb-4900-8fca-0f8ad30c5bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/img[2]</value>
      <webElementGuid>4e8566c1-c06e-427d-99c3-e133b7d0f63f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png' and @alt = 'Marker']</value>
      <webElementGuid>9265005c-8e93-43f0-8156-08c34d52e557</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
