<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Street                              _d1922b</name>
   <tag></tag>
   <elementGuidId>67095f16-0bac-4e72-9c09-c1db6511cb89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pilihmap']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pilihmap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>662e87f0-d603-4cde-9e8a-3d02d517d87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select</value>
      <webElementGuid>13933290-1d1e-4a72-a625-e6918609649d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pilihmap</value>
      <webElementGuid>46f9e696-7433-4d00-84ae-a3b5cdc19a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Street
                                Hybrid
                                Satellite
                                Terrain
                            </value>
      <webElementGuid>84cce282-e86a-4ac4-a24d-47b1b69ebb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pilihmap&quot;)</value>
      <webElementGuid>ec3d555d-5994-46d9-aef6-f264a7db9670</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pilihmap']</value>
      <webElementGuid>c5e9c52c-86e1-4942-84ae-ea6282939f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peta Kabupaten Tabalong'])[1]/following::select[1]</value>
      <webElementGuid>184f1b92-b907-494a-8ede-dff9e8b811aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Peta'])[1]/following::select[1]</value>
      <webElementGuid>8712955c-91df-4af0-b568-38d9a5b8455c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leaflet'])[1]/preceding::select[3]</value>
      <webElementGuid>70a5ae3c-a694-4fc8-a848-7b5d0d0626c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Sekolah'])[1]/preceding::select[5]</value>
      <webElementGuid>dc0992a9-065e-4b18-a415-f82c204a08a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>dc197148-ead9-484b-a3d4-c7632c1e6cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'pilihmap' and (text() = '
                                Street
                                Hybrid
                                Satellite
                                Terrain
                            ' or . = '
                                Street
                                Hybrid
                                Satellite
                                Terrain
                            ')]</value>
      <webElementGuid>caafd820-ae49-4b65-8aa0-bafba1bcc8e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
