<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Semua Jenjang                       _7db837</name>
   <tag></tag>
   <elementGuidId>5afd90bb-1a04-45c8-b4f2-61996497ff9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='filterjenjangTable']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#filterjenjangTable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6d7cd619-9f1a-4a1b-a9e2-f1c8ed35a03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select</value>
      <webElementGuid>219e8304-2439-4a6c-964a-5641b431f0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filterjenjangTable</value>
      <webElementGuid>94ddf611-3773-4142-9118-3b2ae4ad043e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Semua Jenjang
                        SD
                        SMP
                        SMA
                    </value>
      <webElementGuid>d8eb2da0-6915-4902-aa95-0359b5fee435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterjenjangTable&quot;)</value>
      <webElementGuid>b3f90982-2410-4233-ba5b-c5f08a0e3148</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='filterjenjangTable']</value>
      <webElementGuid>17b2a875-398d-4f6b-b711-616a6db67481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leaflet'])[1]/following::select[2]</value>
      <webElementGuid>c6a73d49-d155-44e3-8fce-7cba38c7066d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peta Kabupaten Tabalong'])[1]/following::select[5]</value>
      <webElementGuid>1239d1cd-e101-4769-b5a9-f99da4f9fd26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Sekolah'])[1]/preceding::select[1]</value>
      <webElementGuid>5a073ace-853a-4cbb-a808-b301e591f9ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenjang'])[1]/preceding::select[1]</value>
      <webElementGuid>b272e7ca-2f40-41a8-a1ba-19ab891de4b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div/div[2]/select</value>
      <webElementGuid>6ce9df37-4c3b-4b9c-97bd-ed2295b7b4de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'filterjenjangTable' and (text() = '
                        Semua Jenjang
                        SD
                        SMP
                        SMA
                    ' or . = '
                        Semua Jenjang
                        SD
                        SMP
                        SMA
                    ')]</value>
      <webElementGuid>ea5ee9c1-d4cf-45f8-bfa5-66e966916e8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
