<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Semua Jenjang                       _5385bd</name>
   <tag></tag>
   <elementGuidId>75ec656e-b907-4caa-a39f-ddea315e5d4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='filterjenjang']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#filterjenjang</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9a1cb9cf-18cf-4d3d-8f7a-9472e260df50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select</value>
      <webElementGuid>90a1dff2-48f6-489b-b7e6-051661d45aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filterjenjang</value>
      <webElementGuid>5d79e371-3709-41f1-9fae-19b5e4819b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Semua Jenjang
                                SD
                                SMP
                                SMA
                            </value>
      <webElementGuid>c3ec4bc3-d6fc-4cc1-b484-ffa5157bc19f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterjenjang&quot;)</value>
      <webElementGuid>61bcbd48-b254-49f7-8f63-20089477d347</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='filterjenjang']</value>
      <webElementGuid>81c4a0af-9cba-4784-8b78-ca034f2b4350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peta Kabupaten Tabalong'])[1]/following::select[3]</value>
      <webElementGuid>a836b4d0-1af4-4c77-a035-2c25d541cd28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Peta'])[1]/following::select[3]</value>
      <webElementGuid>f9f8b3ae-5bdb-4be4-a658-d65a9cc02b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leaflet'])[1]/preceding::select[1]</value>
      <webElementGuid>9693bf6a-6817-4f99-9b5d-604ce289a8cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Sekolah'])[1]/preceding::select[3]</value>
      <webElementGuid>ba0d0c02-1c4b-4635-9e2e-a20e7ab7a2f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>ef6617cb-e43c-4027-b1ca-4b6ca7db6433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'filterjenjang' and (text() = '
                                Semua Jenjang
                                SD
                                SMP
                                SMA
                            ' or . = '
                                Semua Jenjang
                                SD
                                SMP
                                SMA
                            ')]</value>
      <webElementGuid>b981fabc-6052-4a90-be86-50004ef59c77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
